certirocq_plugin.cmxa: certirocq_plugin.cmx ../../runtime/lib/get_ordinal.o
	$(HIDE)$(TIMER) $(CAMLOPTLINK) ../../runtime/lib/get_ordinal.o $(CAMLDEBUG) $(CAMLFLAGS) $(FINDLIBPKGS) -a -o $@ $<

g_certirocq.ml: g_certirocq.mlg ../common/certirocq_commands.mlg
	$(SHOW)'CPP+COQPP $<'
	$(HIDE)tmp=$$(mktemp /tmp/g_certirocq.XXXXXX.mlg); \
		cpp -traditional-cpp -P $< > $$tmp; \
		$(COQPP) $$tmp; \
		mv $${tmp%.mlg}.ml $@; \
		rm -f $$tmp
